#!/usr/bin/env python3
"""Generate the WordPress theme's static templates from the design prototypes.

    python3 theme/build-theme.py

design/ stays the single source of truth for markup and styling:
  design/src/partials/header.html  -> header.php
  design/src/partials/footer.html  -> footer.php
  design/src/pages/<page>.html     -> front-page.php / page-templates/*.php / 404.php
  design/assets/*                  -> assets/ (via sync-assets.sh)

Transformations:
  href="about.html#x"  -> href="<?php echo esc_url( mb_link( 'about', 'x' ) ); ?>"
  assets/img/...       -> <?php echo MB_URI; ?>/assets/img/...
  <!--wp:NAME-->…<!--/wp:NAME-->  -> get_template_part( 'template-parts/NAME' )
Dynamic templates (single, archives, portfolio, faq) are hand-written and not touched.
"""
import pathlib, re, subprocess, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DESIGN = ROOT / "design"
THEME = ROOT / "theme" / "milad-bahrami"
sys.path.insert(0, str(DESIGN))
import build as design_build  # noqa: E402  (reuses the long-form content renderer)

GENERATED = "<?php /* GENERATED by theme/build-theme.py from design/ — edit the design source, not this file. */ ?>\n"

PAGES = {
    # design page      output file                              header
    "index":      ("front-page.php",                        ""),
    "service":    ("page-templates/service-consulting.php", "Template Name: لندینگ مشاوره کسب‌وکار"),
    "about":      ("page-templates/about.php",              "Template Name: درباره من"),
    "book":       ("page-templates/book.php",               "Template Name: لندینگ کتاب سلطان قیف\n * Template Post Type: post, page"),
    "chapter":    ("page-templates/chapter.php",            "Template Name: فصل رایگان سلطان قیف"),
    "assessment": ("page-templates/assessment.php",         "Template Name: ارزیابی سازمان"),
    "404":        ("404.php",                               ""),
}


def php_links(html):
    def repl(m):
        attr, key, frag = m.group(1), m.group(2), m.group(3) or ""
        args = f"'{key}'" + (f", '{frag}'" if frag else "")
        return f'{attr}="<?php echo esc_url( mb_link( {args} ) ); ?>"'
    html = re.sub(r'(href|action)="([\w-]+)\.html(?:#([\w-]+))?"', repl, html)
    return html.replace("assets/img/", "<?php echo esc_url( MB_URI ); ?>/assets/img/")


def php_parts(html):
    def repl(m):
        name, attrs = m.group(1), dict(re.findall(r'(\w+)="([^"]*)"', m.group(2) or ""))
        args = ", ".join(f"'{k}' => '{v}'" for k, v in attrs.items())
        return f"<?php get_template_part( 'template-parts/{name}', null, array( {args} ) ); ?>" if args \
            else f"<?php get_template_part( 'template-parts/{name}' ); ?>"
    return re.sub(r"<!--wp:([\w-]+)((?:\s+\w+=\"[^\"]*\")*)\s*-->.*?<!--/wp:\1-->", repl, html, flags=re.S)


def page_body(name):
    raw = (DESIGN / "src/pages" / f"{name}.html").read_text(encoding="utf-8")
    body = re.sub(r"^\s*<!--meta .*?-->\s*", "", raw, flags=re.S)
    body = design_build.expand_includes(body)
    return php_links(php_parts(body))


def header_php():
    partial = php_links((DESIGN / "src/partials/header.html").read_text(encoding="utf-8"))
    return GENERATED + """<!doctype html>
<html <?php language_attributes(); ?>>
<head>
<meta charset="<?php bloginfo( 'charset' ); ?>">
<meta name="viewport" content="width=device-width, initial-scale=1">
<?php wp_head(); ?>
</head>
<body <?php body_class(); ?> data-page="<?php echo esc_attr( mb_page_key() ); ?>">
<?php wp_body_open(); ?>
<a class="skip" href="#main">پرش به محتوای اصلی</a>
<div class="progress" aria-hidden="true"></div>

""" + partial + '\n<main id="main">\n'


def footer_php():
    partial = php_links((DESIGN / "src/partials/footer.html").read_text(encoding="utf-8"))
    partial = partial.replace("© ۱۴۰۵", "© <?php echo esc_html( mb_fa_digits( wp_date( 'Y', null, new DateTimeZone( 'Asia/Tehran' ) ) ) ); ?>")
    return GENERATED + "</main>\n\n" + partial + "\n<?php wp_footer(); ?>\n</body>\n</html>\n"


def template_php(name, header):
    head = GENERATED
    if header:
        head = "<?php\n/**\n * " + header + "\n *\n * GENERATED by theme/build-theme.py from design/src/pages/" + name + ".html\n */\n?>\n"
    return head + "<?php get_header(); ?>\n" + page_body(name) + "\n<?php get_footer(); ?>\n"


def patterns():
    """Each funnel section of the consulting landing becomes a reusable block pattern
    (wp:html) so the other service pages are assembled from the same sections."""
    body = page_body("service")
    parts = re.split(r"(<!-- ============ (.*?) ============ -->)", body)
    out_dir = THEME / "patterns"
    for f in out_dir.glob("service-*.php"):
        f.unlink()
    n = 0
    for i in range(1, len(parts), 3):
        title, html = parts[i + 1].strip(), parts[i + 2].strip()
        if not html or "phero" in html:
            continue  # the hero comes from the page title/excerpt in page-templates/service.php
        n += 1
        slug = f"service-{n:02d}"
        (out_dir / f"{slug}.php").write_text(
            "<?php\n/**\n * Title: خدمت — " + title + "\n * Slug: mb/" + slug +
            "\n * Categories: mb-sections\n * Description: GENERATED from design/src/pages/service.html\n */\n?>\n"
            "<!-- wp:html -->\n" + html + "\n<!-- /wp:html -->\n", encoding="utf-8")
    print(f"   patterns/service-*.php ({n})")


def main():
    subprocess.run([str(ROOT / "theme/sync-assets.sh")], check=True)
    (THEME / "page-templates").mkdir(exist_ok=True)
    (THEME / "header.php").write_text(header_php(), encoding="utf-8")
    (THEME / "footer.php").write_text(footer_php(), encoding="utf-8")
    for name, (out, header) in PAGES.items():
        (THEME / out).write_text(template_php(name, header), encoding="utf-8")
        print("  ", out)
    patterns()
    left = sorted({m for f in THEME.rglob("*.php") for m in re.findall(r'href="([\w-]+\.html[^"]*)"', f.read_text(encoding="utf-8"))})
    if left:
        print("unmapped .html links:", left)


if __name__ == "__main__":
    main()
