<?php
/**
 * Template Name: لندینگ کتاب سلطان قیف
 * Template Post Type: post, page
 *
 * GENERATED by theme/build-theme.py from design/src/pages/book.html
 */
?>
<?php get_header(); ?>
<!-- ============ ۱ · توجه ============ -->
<section class="phero on-dark book-hero">
  <div class="wrap phero-grid">
    <div class="rise">
      <ol class="crumbs" aria-label="مسیر صفحه"><li><a href="<?php echo esc_url( mb_link( 'index' ) ); ?>">خانه</a></li><li aria-current="page">کتاب سلطان قیف</li></ol>
      <div class="chips" style="margin-top:22px"><span class="chip gold">انتشار ۲۰۲۶</span><span class="chip">مدیریت استراتژیک فروش</span></div>
      <h1>سلطان قیف <span class="grad">Funnel King</span></h1>
      <p class="lead" style="color:#fff;font-weight:600">مدیریت استراتژیک فروش در بازارهای بحرانی و رقابتی</p>
      <p class="lead" style="margin-top:10px">راهنمای عملی طراحی قیف فروش، افزایش نرخ تبدیل، کاهش هزینه‌ی جذب مشتری و ساخت سیستم فروش پایدار برای کسب‌وکارها.</p>
      <div class="ctas"><a class="btn btn-gold" href="https://funnelking.ir" target="_blank" rel="noopener">خرید از funnelking.ir</a><a class="btn btn-line" href="<?php echo esc_url( mb_link( 'chapter' ) ); ?>">خواندن رایگان فصل اول</a></div>
      <div class="facts" style="display:flex;flex-wrap:wrap;gap:10px 22px;margin-top:32px;font-size:14px;color:var(--ink-300)"><span>تألیف: محمدامین بهرامی</span><span>۱۱ بخش</span><span dir="ltr">ISBN 978-622-94021-9-1</span></div>
    </div>
    <div class="stage rise" style="--d:150ms">
      <div class="cover3d img"><picture><source type="image/webp" srcset="<?php echo esc_url( MB_URI ); ?>/assets/img/funnel-king-360.webp 360w, <?php echo esc_url( MB_URI ); ?>/assets/img/funnel-king-720.webp 720w" sizes="280px"><img src="<?php echo esc_url( MB_URI ); ?>/assets/img/funnel-king-720.jpg" alt="جلد کتاب سلطان قیف (Funnel King) نوشته‌ی محمدامین بهرامی" width="720" height="1001" loading="eager" decoding="async"></picture></div>
    </div>
  </div>
</section>

<!-- ============ ۲ · مسئله ============ -->
<section class="sec">
  <div class="wrap">
    <div class="sec-head" data-reveal style="max-width:760px"><span class="eyebrow">چرا این کتاب؟</span><h2 class="h2">سلطان قیف فقط یک کتاب فروش نیست!</h2><p class="lead">نقشه‌ای برای ساختن یک ماشین رشد پایدار است. در بازاری که هر روز با بحران، رقابت و بی‌ثباتی روبه‌روست، بقا کافی نیست؛ باید سیستم ساخت. این کتاب عصاره‌ی تجربه‌های میدانی، تحلیل داده‌های واقعی و طراحی قیف‌هایی است که در بازار ایران واقعاً کار می‌کنند.</p></div>
    <div class="grid-3">
      <div class="card" data-reveal><h3>فروش به فروشنده‌ی خوب وابسته است</h3><p>با رفتن یک نفر، نیمی از فروش هم می‌رود.</p></div>
      <div class="card" data-reveal style="--d:70ms"><h3>تبلیغات بیشتر، سود کمتر</h3><p>بودجه‌ی بیشتر فقط ریزش را بزرگ‌تر کرده است.</p></div>
      <div class="card" data-reveal style="--d:140ms"><h3>مشتری یک‌بار می‌خرد و نمی‌ماند</h3><p>بعد از خرید، هیچ سیستمی برای وفادارسازی نیست.</p></div>
    </div>
  </div>
</section>

<!-- ============ ۳ · راه‌حل: فهرست فصل‌ها ============ -->
<section class="sec band">
  <div class="wrap">
    <div class="sec-head" data-reveal><span class="eyebrow">داخل کتاب</span><h2 class="h2">فهرست کتاب: ۱۱ بخش، از DNA استراتژی تا ابزارهای اجرا</h2></div>
    <ol class="toc-book" style="margin:0;padding:0" data-reveal>
      <li data-n="•"><div><b>پیشگفتار</b><small>صفحه‌ی ۴</small></div></li>
      <li data-n="•"><div><b>پیش‌درآمد و قرارداد خواندن</b><small>صفحه‌ی ۱۱</small></div></li>
      <li data-n="۱" class="free"><div><b><a href="<?php echo esc_url( mb_link( 'chapter' ) ); ?>">DNA تفکر استراتژیک</a></b><small>صفحه‌ی ۱۷</small></div></li>
      <li data-n="۲"><div><b>بازیِ بازار: نیروها، بازیگران، قواعد</b><small>صفحه‌ی ۵۱</small></div></li>
      <li data-n="۳"><div><b>مهندسی قیف به‌عنوان موتور رشد</b><small>صفحه‌ی ۹۴</small></div></li>
      <li data-n="۴"><div><b>محصول و ارزش پیشنهادی: ساختن چیزی که می‌ماند</b><small>صفحه‌ی ۱۳۳</small></div></li>
      <li data-n="۵"><div><b>مدل کسب‌وکار و پول</b><small>صفحه‌ی ۱۶۵</small></div></li>
      <li data-n="۶"><div><b>عملیات و ظرفیت</b><small>صفحه‌ی ۲۰۵</small></div></li>
      <li data-n="۷"><div><b>سازمان، تصمیم‌گیری و اجرا</b><small>صفحه‌ی ۲۳۷</small></div></li>
      <li data-n="۸"><div><b>استراتژی ورود به بازار (GTM)</b><small>صفحه‌ی ۲۵۳</small></div></li>
      <li data-n="۹"><div><b>بحران، ضدشکنندگی و بازی‌های قدرت</b><small>صفحه‌ی ۲۷۹</small></div></li>
      <li data-n="۱۰"><div><b>روایت آموزشیِ «سلطان قیف»؛ بازی واقعی رشد</b><small>صفحه‌ی ۳۲۱</small></div></li>
      <li data-n="۱۱"><div><b>دستور کارها، تمرین‌ها و ابزارها</b><small>صفحه‌ی ۳۲۷</small></div></li>
    </ol>
  </div>
</section>

<!-- ============ ۴ · پرورش: پیش‌نمایش فصل اول (Lead magnet باز) ============ -->
<section class="sec" id="sample">
  <div class="wrap">
    <div class="sec-head" data-reveal style="text-align:center;justify-items:center"><span class="eyebrow">پیش‌نمایش</span><h2 class="h2">فصل اول را رایگان بخوانید</h2></div>
    <div class="excerpt" data-reveal>
      <div class="fade prose book-prose">
        <p>اگر قرار باشد تمام مدیریت استراتژیک را در یک جمله فشرده کنیم، شاید این جمله از همه دقیق‌تر باشد:</p>
        <blockquote>استراتژی یعنی تصمیم گرفتن زیر فشار، با منابع محدود، در شرایطی که نمی‌توان همه گزینه‌های خوب را هم‌زمان داشت.</blockquote>
        <p>بیشتر آدم‌ها استراتژی را با برنامه‌ریزی بلندمدت اشتباه می‌گیرند. بعضی‌ها هم آن را با بلندپروازی یکی می‌دانند. عده‌ای تصور می‌کنند استراتژی همان فایل پاورپوینتی است که سالی یک‌بار در جلسه مدیران ارائه می‌شود؛ پر از فلش، دایره، نمودار، کلمات بزرگ و جمله‌های الهام‌بخش.</p>
        <p>اما در دنیای واقعی، استراتژی هیچ‌کدام از این‌ها نیست.</p>
        <p>استراتژی یعنی وقتی با پنج فرصت جذاب، سه تهدید واقعی، بودجه محدود، تیم ناقص، زمان کم و بازاری نامطمئن روبه‌رو هستی، بتوانی تصمیم بگیری…</p>
      </div>
      <div class="more"><a class="btn btn-ink" href="<?php echo esc_url( mb_link( 'chapter' ) ); ?>">ادامه‌ی فصل اول</a><a class="btn btn-line" href="<?php echo esc_url( mb_link( 'chapter', 'canvas' ) ); ?>">بوم Strategic DNA</a></div>
    </div>
  </div>
</section>

<!-- ============ ۴ب · محتوای موجود صفحه (حفظ سئو) ============ -->
<?php get_template_part( 'template-parts/content', null, array( 'title' => 'درباره‌ی کتاب سلطان قیف' ) ); ?>

<!-- ============ ۵ · اعتبار + خرید ============ -->
<section class="sec band" id="buy">
  <div class="wrap buy-grid" data-reveal>
    <div>
      <span class="eyebrow">برای چه کسی؟</span>
      <h2 class="h2" style="margin:14px 0 18px">برای مدیرانی که فروش را سیستم می‌خواهند، نه شانس</h2>
      <div class="fit" style="grid-template-columns:1fr">
        <div class="card yes"><ul>
          <li><svg width="14" height="14" viewBox="0 0 14 14" fill="none" aria-hidden="true"><path d="m2.5 7.5 3 3 6-7" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>صاحبان کسب‌وکار و مدیران فروش</li>
          <li><svg width="14" height="14" viewBox="0 0 14 14" fill="none" aria-hidden="true"><path d="m2.5 7.5 3 3 6-7" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>تیم‌های فروش B2B و B2C</li>
          <li><svg width="14" height="14" viewBox="0 0 14 14" fill="none" aria-hidden="true"><path d="m2.5 7.5 3 3 6-7" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>بازاریاب‌هایی که می‌خواهند اثر کارشان را اندازه بگیرند</li>
        </ul></div>
      </div>
      <div class="author" style="margin-top:22px">
        <span class="avatar"><picture><source type="image/webp" srcset="<?php echo esc_url( MB_URI ); ?>/assets/img/avatar-240.webp"><img src="<?php echo esc_url( MB_URI ); ?>/assets/img/avatar-240.jpg" alt="" width="240" height="240" loading="lazy"></picture></span>
        <div><b>محمدامین (میلاد) بهرامی</b><div class="role">مؤلف</div><p>مشاور سیستم‌سازی و تحول سازمانی و مدیرعامل اکسیر تجارت امین.</p><p style="font-size:14px;color:var(--text-3)">با همکاری: سید محمدحسن حسینی شرقی، محمدپارسا جوادی، سیده شقایق حسینی، معین نورآسیایی، کوشا کریمی</p><div class="links"><a href="<?php echo esc_url( mb_link( 'about' ) ); ?>">درباره‌ی نویسنده</a></div></div>
      </div>
    </div>
    <div class="buy">
      <span class="chip light" style="justify-self:start">نسخه‌ی چاپی</span>
      <div class="price" style="font-size:24px">خرید آنلاین از سایت رسمی کتاب</div>
      <div class="ebook"><span>نسخه‌ی الکترونیکی</span><b>۸۵۰٬۰۰۰ <small>تومان</small></b></div>
      <ul>
        <li><svg width="14" height="14" viewBox="0 0 14 14" fill="none" aria-hidden="true"><path d="m2.5 7.5 3 3 6-7" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>ارسال به سراسر ایران</li>
        <li><svg width="14" height="14" viewBox="0 0 14 14" fill="none" aria-hidden="true"><path d="m2.5 7.5 3 3 6-7" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>امضای نویسنده (به درخواست)</li>
        <li><svg width="14" height="14" viewBox="0 0 14 14" fill="none" aria-hidden="true"><path d="m2.5 7.5 3 3 6-7" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>دسترسی به قالب‌های قیف فروش</li>
      </ul>
      <a class="btn btn-gold" href="https://funnelking.ir" target="_blank" rel="noopener" style="width:100%">funnelking.ir</a>
      <small style="color:var(--text-3);text-align:center">برای خرید سازمانی (بیش از ۱۰ نسخه) <a href="<?php echo esc_url( mb_link( 'assessment', 'contact' ) ); ?>" style="color:var(--gold-text);font-weight:700">تماس بگیرید</a></small>
    </div>
  </div>
</section>

<!-- ============ ۶ · رفع تردید ============ -->
<section class="sec">
  <div class="wrap faq">
    <div data-reveal><span class="eyebrow">پرسش‌های رایج</span><h2 class="h2" style="margin-top:14px">درباره‌ی کتاب</h2></div>
    <div data-reveal style="--d:80ms">
      <details open><summary>کتاب برای چه سطحی نوشته شده؟<span class="pm" aria-hidden="true"><svg width="12" height="12" viewBox="0 0 12 12"><path d="M6 1v10M1 6h10" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg></span></summary><p>برای مدیران و صاحبان کسب‌وکار؛ بدون نیاز به دانش تخصصی بازاریابی.</p></details>
      <details><summary>نسخه‌ی الکترونیکی دارد؟<span class="pm" aria-hidden="true"><svg width="12" height="12" viewBox="0 0 12 12"><path d="M6 1v10M1 6h10" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg></span></summary><p>بله. نسخه‌ی الکترونیکی کتاب ۸۵۰٬۰۰۰ تومان است و از <a href="https://funnelking.ir" target="_blank" rel="noopener" style="color:var(--gold-text);font-weight:700">funnelking.ir</a> قابل خرید است.</p></details>
      <details><summary>می‌توانم قبل از خرید بخشی از کتاب را بخوانم؟<span class="pm" aria-hidden="true"><svg width="12" height="12" viewBox="0 0 12 12"><path d="M6 1v10M1 6h10" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg></span></summary><p>بله. <a href="<?php echo esc_url( mb_link( 'chapter' ) ); ?>" style="color:var(--gold-text);font-weight:700">متن کامل بخش اول</a> همراه با بوم Strategic DNA رایگان در دسترس است.</p></details>
      <details><summary>کتاب با مشاوره قیف فروش چه ارتباطی دارد؟<span class="pm" aria-hidden="true"><svg width="12" height="12" viewBox="0 0 12 12"><path d="M6 1v10M1 6h10" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg></span></summary><p>کتاب متد را توضیح می‌دهد؛ در مشاوره، همان متد روی داده‌های کسب‌وکار شما پیاده می‌شود.</p></details>
    </div>
  </div>
</section>

<!-- ============ ۷ · ارتقا: از کتاب تا مشاوره ============ -->
<section style="padding-bottom:0">
  <div class="wrap">
    <div class="cta-band on-dark" data-reveal>
      <div><h2>می‌خواهید قیف فروش شما را با هم بسازیم؟</h2><p>متد کتاب، روی داده‌های واقعی کسب‌وکار شما.</p></div>
      <div class="ctas"><a class="btn btn-gold" href="<?php echo esc_url( mb_link( 'assessment' ) ); ?>">مشاوره قیف فروش</a><a class="btn btn-line" href="<?php echo esc_url( mb_link( 'article' ) ); ?>">قیف فروش چیست؟</a></div>
    </div>
  </div>
</section>

<?php get_footer(); ?>
