<?php /* GENERATED by theme/build-theme.py from design/ — edit the design source, not this file. */ ?>
<?php get_header(); ?>
<section class="phero on-dark nf">
  <div class="wrap">
    <div class="rise" style="max-width:720px">
      <div class="code" aria-hidden="true">۴۰۴</div>
      <h1 style="font-size:clamp(28px,3.4vw,40px)">این صفحه در سیستم ما نیست</h1>
      <p class="lead">شاید آدرس تغییر کرده باشد. از جستجو یا مسیرهای پرکاربرد زیر استفاده کنید.</p>
      <form class="search" role="search" action="<?php echo esc_url( mb_link( 'blog' ) ); ?>"><input type="search" name="s" placeholder="جستجو در سایت…" aria-label="جستجو در سایت"><svg width="18" height="18" viewBox="0 0 18 18" fill="none" aria-hidden="true"><circle cx="8" cy="8" r="5.5" stroke="currentColor" stroke-width="1.6"/><path d="m12.5 12.5 3.5 3.5" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg></form>
      <div class="chips" style="margin-top:26px">
        <a class="chip" href="<?php echo esc_url( mb_link( 'service' ) ); ?>">مشاوره کسب‌وکار</a><a class="chip" href="<?php echo esc_url( mb_link( 'index', 'method' ) ); ?>">متد سیستم‌سازی</a><a class="chip" href="<?php echo esc_url( mb_link( 'blog' ) ); ?>">دانشنامه</a><a class="chip" href="<?php echo esc_url( mb_link( 'book' ) ); ?>">کتاب سلطان قیف</a><a class="chip gold" href="<?php echo esc_url( mb_link( 'assessment' ) ); ?>">ارزیابی سازمان</a>
      </div>
    </div>
  </div>
</section>

<?php get_footer(); ?>
