<?php /* GENERATED by theme/build-theme.py from design/ — edit the design source, not this file. */ ?>
</main>

<!-- ============ FOOTER ============ -->
<footer>
  <div class="wrap">
    <div class="cols">
      <div>
        <a class="brand" href="<?php echo esc_url( mb_link( 'index' ) ); ?>"><span class="mark" aria-hidden="true"><svg width="24" height="24" viewBox="0 0 26 26" fill="none"><circle cx="5" cy="13" r="3" fill="#E6C98E"/><circle cx="21" cy="5" r="3" stroke="#fff" stroke-width="1.8"/><circle cx="21" cy="21" r="3" stroke="#fff" stroke-width="1.8"/><path d="M8 13h5m0 0V6.5a1.5 1.5 0 0 1 1.5-1.5H18M13 13v6.5a1.5 1.5 0 0 0 1.5 1.5H18" stroke="#fff" stroke-width="1.8" stroke-linecap="round"/></svg></span><span><b>میلاد بهرامی</b><small>مشاور سیستم‌سازی و تحول سازمانی</small></span></a>
        <p class="bio">مدیرعامل اکسیر تجارت امین؛ متخصص معماری فرآیند، ERP، BPMS و اتوماسیون؛ نویسنده‌ی کتاب سلطان قیف.</p>
        <div class="social"><a href="https://www.linkedin.com/in/thisismbahrami/" target="_blank" rel="noopener" aria-label="لینکدین میلاد بهرامی"><svg width="18" height="18" viewBox="0 0 18 18" fill="none" aria-hidden="true"><rect x="2.5" y="2.5" width="13" height="13" rx="3" stroke="currentColor" stroke-width="1.5"/><path d="M6 8v4.5M6 5.8v.1M9 12.5V10a1.8 1.8 0 0 1 3.6 0v2.5M9 8v4.5" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/></svg></a><a href="https://instagram.com/thisismbahrami" target="_blank" rel="noopener" aria-label="اینستاگرام میلاد بهرامی"><svg width="18" height="18" viewBox="0 0 18 18" fill="none" aria-hidden="true"><rect x="2.5" y="2.5" width="13" height="13" rx="4" stroke="currentColor" stroke-width="1.5"/><circle cx="9" cy="9" r="3" stroke="currentColor" stroke-width="1.5"/><circle cx="13" cy="5" r=".9" fill="currentColor"/></svg></a><a href="https://wa.me/message/OLOSVHQC6HTCP1" target="_blank" rel="noopener" aria-label="گفتگو در واتس‌اپ"><svg width="18" height="18" viewBox="0 0 18 18" fill="none" aria-hidden="true"><path d="M3 15l1-3.2A6.5 6.5 0 1 1 6.3 14z" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/><path d="M6.8 6.2c0 2.6 2.4 5 5 5l.9-1.3-1.6-.8-.7.6a3.6 3.6 0 0 1-1.9-1.9l.6-.7-.8-1.6z" fill="currentColor"/></svg></a></div>
      </div>
      <div><h4>خدمات</h4><ul><li><a href="<?php echo esc_url( mb_link( 'service' ) ); ?>">مشاوره کسب‌وکار</a></li><li><a href="#">سیستم‌سازی سازمانی</a></li><li><a href="#">معماری فرآیند</a></li><li><a href="#">عارضه‌یابی سازمان</a></li><li><a href="#">مشاوره ERP</a></li><li><a href="#">مشاوره BPMS</a></li></ul></div>
      <div><h4>منابع</h4><ul><li><a href="<?php echo esc_url( mb_link( 'blog' ) ); ?>">دانشنامه</a></li><li><a href="<?php echo esc_url( mb_link( 'projects' ) ); ?>">نمونه‌کارها</a></li><li><a href="<?php echo esc_url( mb_link( 'book' ) ); ?>">کتاب سلطان قیف</a></li><li><a href="https://funnelking.ir" target="_blank" rel="noopener">funnelking.ir</a></li><li><a href="<?php echo esc_url( mb_link( 'faq' ) ); ?>">سوالات متداول</a></li><li><a href="<?php echo esc_url( mb_link( 'about' ) ); ?>">درباره من</a></li></ul></div>
      <div><h4>تماس</h4><address class="nap"><a href="tel:+989908008011" dir="ltr">۰۹۹۰ ۸۰۰ ۸۰۱۱</a><a href="https://wa.me/message/OLOSVHQC6HTCP1" target="_blank" rel="noopener">گفتگو در واتس‌اپ</a><span>شیراز، حدفاصل تپه تلویزیون و میدان ارم، ساختمان مدیریت دانشگاه شیراز، طبقه‌ی ۸، آفیس ۸۰۶</span><a href="https://exirerp.ir/book/coaching">درخواست مشاوره کسب‌وکار</a><a href="<?php echo esc_url( mb_link( 'assessment' ) ); ?>">درخواست ارزیابی سازمان</a></address></div>
    </div>
    <div class="legal"><span>© <?php echo esc_html( mb_fa_digits( wp_date( 'Y', null, new DateTimeZone( 'Asia/Tehran' ) ) ) ); ?> میلاد بهرامی · thisismbahrami.ir</span><span>مشاور کسب‌وکار و سیستم‌سازی در شیراز و سراسر ایران</span></div>
  </div>
</footer>

<?php wp_footer(); ?>
</body>
</html>
