<?php /* GENERATED by theme/build-theme.py from design/ — edit the design source, not this file. */ ?>
<!doctype html>
<html <?php language_attributes(); ?>>
<head>
<meta charset="<?php bloginfo( 'charset' ); ?>">
<meta name="viewport" content="width=device-width, initial-scale=1">
<?php wp_head(); ?>
</head>
<body <?php body_class(); ?> data-page="<?php echo esc_attr( mb_page_key() ); ?>">
<?php wp_body_open(); ?>
<a class="skip" href="#main">پرش به محتوای اصلی</a>
<div class="progress" aria-hidden="true"></div>

<!-- ============ HEADER ============ -->
<header class="hdr" id="hdr">
  <div class="wrap">
    <a class="brand" href="<?php echo esc_url( mb_link( 'index' ) ); ?>" aria-label="میلاد بهرامی — صفحه‌ی اصلی">
      <span class="mark" aria-hidden="true">
        <svg width="24" height="24" viewBox="0 0 26 26" fill="none"><circle cx="5" cy="13" r="3" fill="#E6C98E"/><circle cx="21" cy="5" r="3" stroke="#fff" stroke-width="1.8"/><circle cx="21" cy="21" r="3" stroke="#fff" stroke-width="1.8"/><path d="M8 13h5m0 0V6.5a1.5 1.5 0 0 1 1.5-1.5H18M13 13v6.5a1.5 1.5 0 0 0 1.5 1.5H18" stroke="#fff" stroke-width="1.8" stroke-linecap="round"/></svg>
      </span>
      <span><b>میلاد بهرامی</b><small>سیستم‌سازی و تحول سازمانی</small></span>
    </a>
    <nav class="nav" aria-label="منوی اصلی">
      <a href="<?php echo esc_url( mb_link( 'index', 'method' ) ); ?>" data-nav="method">متد</a>
      <div class="has-mega">
        <button type="button" class="mega-btn" aria-expanded="false" aria-controls="mega" data-nav="services">خدمات
          <svg width="12" height="12" viewBox="0 0 12 12" fill="none" aria-hidden="true"><path d="m3 4.5 3 3 3-3" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></svg></button>
        <div class="mega" id="mega">
          <div class="mega-col">
            <span class="mega-h">شروع مسیر</span>
            <a href="<?php echo esc_url( mb_link( 'service' ) ); ?>"><b>مشاوره کسب‌وکار</b><small>راه‌اندازی، توسعه، استراتژی</small></a>
            <a href="#"><b>عارضه‌یابی سازمان</b><small>ریشه‌ی مشکلات و گلوگاه‌ها</small></a>
            <a href="#"><b>مشاوره قیف فروش</b><small>سیستم‌سازی فروش</small></a>
          </div>
          <div class="mega-col">
            <span class="mega-h">سیستم‌سازی</span>
            <a href="#"><b>سیستم‌سازی سازمانی</b><small>کاهش وابستگی به افراد</small></a>
            <a href="#"><b>معماری فرآیند</b><small>BPMN، مستندسازی، بهبود</small></a>
            <a href="#"><b>تحول سازمانی</b><small>نقشه‌ی راه و مدیریت تغییر</small></a>
          </div>
          <div class="mega-col">
            <span class="mega-h">فناوری سازمانی</span>
            <a href="#"><b>مشاوره ERP</b><small>انتخاب، استقرار، نجات پروژه</small></a>
            <a href="#"><b>مشاوره BPMS</b><small>گردش‌کار و اتوماسیون فرآیند</small></a>
            <a href="#"><b>اتوماسیون کسب‌وکار</b><small>حذف کارهای تکراری</small></a>
          </div>
          <a class="mega-cta" href="<?php echo esc_url( mb_link( 'index', 'diagnosis' ) ); ?>">
            <span class="k">مطمئن نیستید از کجا شروع کنید؟</span>
            <b>خودارزیابی ۳۰ ثانیه‌ای</b>
            <svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-hidden="true"><path d="M13 8H3m0 0 4-4M3 8l4 4" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></svg>
          </a>
        </div>
      </div>
      <a href="<?php echo esc_url( mb_link( 'index', 'products' ) ); ?>" data-nav="products">محصولات</a>
      <a href="<?php echo esc_url( mb_link( 'about' ) ); ?>" data-nav="about">درباره من</a>
      <a href="<?php echo esc_url( mb_link( 'book' ) ); ?>" data-nav="book">سلطان قیف</a>
      <a href="<?php echo esc_url( mb_link( 'blog' ) ); ?>" data-nav="blog">دانشنامه</a>
    </nav>
    <div class="hdr-ctas"><a class="btn hdr-book" href="https://exirerp.ir/book/coaching">درخواست مشاوره</a><a class="btn btn-gold cta-desk" href="<?php echo esc_url( mb_link( 'assessment' ) ); ?>">ارزیابی سازمان</a></div>
    <button class="burger" aria-label="باز کردن منو" aria-expanded="false" aria-controls="drawer" id="burger">
      <svg width="20" height="20" viewBox="0 0 20 20" fill="none" aria-hidden="true"><path d="M3 6h14M3 10h14M3 14h9" stroke="#fff" stroke-width="1.8" stroke-linecap="round"/></svg>
    </button>
  </div>
</header>
<div class="drawer" id="drawer" aria-hidden="true">
  <div class="panel" role="dialog" aria-label="منو">
    <button class="close" id="drawerClose" aria-label="بستن منو"><svg width="18" height="18" viewBox="0 0 18 18" fill="none" aria-hidden="true"><path d="M4 4l10 10M14 4 4 14" stroke="#fff" stroke-width="1.8" stroke-linecap="round"/></svg></button>
    <a href="<?php echo esc_url( mb_link( 'index', 'method' ) ); ?>">متد</a>
    <details class="drawer-group"><summary>خدمات</summary>
      <a href="<?php echo esc_url( mb_link( 'service' ) ); ?>">مشاوره کسب‌وکار</a><a href="#">سیستم‌سازی سازمانی</a><a href="#">معماری فرآیند</a><a href="#">عارضه‌یابی سازمان</a><a href="#">مشاوره ERP</a><a href="#">مشاوره BPMS</a><a href="#">اتوماسیون کسب‌وکار</a><a href="#">مشاوره قیف فروش</a>
    </details>
    <a href="<?php echo esc_url( mb_link( 'index', 'products' ) ); ?>">محصولات</a><a href="<?php echo esc_url( mb_link( 'projects' ) ); ?>">نمونه‌کارها</a><a href="<?php echo esc_url( mb_link( 'about' ) ); ?>">درباره من</a><a href="<?php echo esc_url( mb_link( 'book' ) ); ?>">سلطان قیف</a><a href="<?php echo esc_url( mb_link( 'blog' ) ); ?>">دانشنامه</a><a href="<?php echo esc_url( mb_link( 'faq' ) ); ?>">سوالات متداول</a>
    <a class="btn btn-gold" href="https://exirerp.ir/book/coaching" style="margin-top:16px">درخواست مشاوره کسب‌وکار</a>
    <a class="btn btn-line" href="<?php echo esc_url( mb_link( 'assessment' ) ); ?>" style="border-color:rgba(255,255,255,.2);color:#fff">ارزیابی سازمان</a>
  </div>
</div>

<main id="main">
